### ISSUE TITLE
Use yarn workspaces

### ISSUE THREAD

**Issue by abdonrd** [Polymer/tools#156]
> Workspaces are a new way to setup your package architecture that’s available by default starting from Yarn 1.0. It allows you to setup multiple packages in such a way that you only need to run `yarn install` once to install all of them in a single pass.

Reference: https://yarnpkg.com/lang/en/docs/workspaces/

**Comment by aomarks** [comment]
Lerna already uses workspaces: https://yarnpkg.com/lang/en/docs/workspaces/#toc-how-does-it-compare-to-lerna

Lerna provides us some higher level operations over the linked workspace which Yarn workspaces alone don't provide.

**Comment by abdonrd** [comment]
I don't say to leave Lerna, I thought about using both.

Reference at `Yarn Workspaces` of [One vs. many — Why we moved from multiple git repos to a monorepo and how we set it up](https://hackernoon.com/one-vs-many-why-we-moved-from-multiple-git-repos-to-a-monorepo-and-how-we-set-it-up-f4abb0cfe469).

(I don't have much experience about this, so maybe I'm wrong)

**Comment by aomarks** [comment]
I actually mistakenly thought that lerna always uses yarn workspaces, but actually it's a setting it has that we haven't tried yet. Definitely something to play with at some point, since it might be faster/more reliable than what lerna is doing by itself.

**Comment by abdonrd** [comment]
Some more info: https://yarnpkg.com/blog/2018/05/18/focused-workspaces/

**Comment by btopro** [comment]
We are using the two together for our components so just reporting this is faster when using the two together rather than lerna alone. Effectively lerna link and lerna publish are the only remaining commands. Workspaces handles everything else.
https://github.com/elmsln/lrnwebcomponents/blob/master/lerna.json
https://github.com/elmsln/lrnwebcomponents/blob/master/package.json#L139

Hope this is useful when revisiting
