### ISSUE TITLE
[cli] Do the script srcs need to be changed in polymer-3.x element template?

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/tools#219]
After creating a polymer 3.0 element from `polymer init`, using polymer-cli version 1.7.0-pre.14, i have to change the script srcs in demo/index.html from

```
<script src="../node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
<script type="module" src="../node_modules/@polymer/iron-demo-helpers/demo-pages-shared-styles.js"></script>
<script type="module" src="../node_modules/@polymer/iron-demo-helpers/demo-snippet.js"></script>
```

to

```
<script src="../../@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
<script type="module" src="../../@polymer/iron-demo-helpers/demo-pages-shared-styles.js></script>
<script type="module" src="../../@polymer/iron-demo-helpers/demo-snippet.js"></script>
```

to get the demo to work.

**Comment by bicknellr** [comment]
I converted the URLs in that template to work with `/demo/` rather than `/components/element-name/demo/` because this is what we eventually want all of the URLs in demo / test HTML files* to use - the demo should work if you go to `/demo/`. Are there any docs pages or tutorials that use the element template from cli and have `polymer serve --open` or tell the user to go to the `/components/...` path?

\* specifically, HTML files that aren't meant to be imported

**Comment by bicknellr** [comment]
These were reverted in https://github.com/Polymer/tools/pull/366.
