### ISSUE TITLE
WCT + Typescript

### ISSUE THREAD

**Issue by FirebladeDan** [Polymer/tools#3468]
How could I configure WCT to work with typescript? The tester responds with a 'WCT searched for .js and .html files matching: test/' of which I could see .js is hardcoded in the error message..

If .ts test files is possible could you please share the config? Thank you

**Comment by lemoustachiste** [comment]
I'd second that,

I have introduced typescript into my project, only one file at this time, but WCT stopped functioning. I have a couple of ideas to solve the issue:
- test the build code rather than files -> defeats the purpose of unit testing
- precompile TS files to JS -> adds some noise, but doable

What I wanted to know is if there was a way to set this up in the wct.conf file, so that this problem would be abstracted away?

Thanks

**Comment by aomarks** [comment]
@lemoustachiste 's second suggestion to precompile TS to JS is a good solution, and what I usually do. It's easy to set up and in my experience doesn't add noise in a way that is disruptive.

Also note that WCT is not in development anymore. I highly recommend starting to migrate to something like Karma. The open-wc docs at https://open-wc.org/testing/testing-karma.html are a good starting point.
