### ISSUE TITLE
polymer init - gitignore issue

### ISSUE THREAD

**Issue by homerjonathan** [Polymer/tools#373]
Using polymer init to create a new Polymer 3.0 element an error occurs.  

> error: [cli.main]   Uncaught exception: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\jhome\AppData\Roaming\npm\node_modules\polymer-cli\templates\element\polymer-3.x\.gitignore

It is trying to copy the .gitignore file which does not exist in version **1.7.0**.  I had to specifically install version **1.7.1** for this to be fixed.

```cmd
npm i -g polymer-cli@1.7.1
```

This seems linked with #343 but is now working if you use the new version, so this is a hint for users who are struggling with this command.

**Comment by web-padawan** [comment]
See the [CLI Changelog](https://github.com/Polymer/tools/blob/master/packages/cli/CHANGELOG.md#v171-05-09-2018), it clearly states that this issue has been fixed in 1.7.1. You don't need to install the specific version, just run `npm i -g polymer-cli` as usual. So I don't see any issue here, and I think this can be closed.

**Comment by homerjonathan** [comment]
Strange on my machine first thing I did was do an npm i -g polymer-cli.  It installed v1.7.0 then I redid with @next and it installed v1.7.0-pre.3.  So I searched for the latest version and ran with @1.7.1 and it finally updated.  Caching issue perhaps?

**Comment by rictic** [comment]
Sounds like this is fixed. npm caching is a biiiiiit of a mystery sometimes :)
