### ISSUE TITLE
[polyserve] Consider adding namespaces into project files

### ISSUE THREAD

**Issue by madiyetov** [Polymer/tools#410]
Now we can use `@polymer` to get package from `node_modules/@polymer` path. Consider using the same for projects components. I see it like this:
1. Add to polymer.json file mapping of the namespaces:
```
{
    '@grid': 'src/components/grid'
}
```
2. Use it in the another component:
```
import grid from '@grid/column.js'
```
3. Polymer serve will convert it to:
```
import grid from '/src/components/grid/column.js'
```

And of course `polymer build` must handle that and check for the conflict with the npm namespaces before processing.

This will be useful in importing some custom libraries with utils which used often. For example custom lodash package which has been generated with lodash-cli:

1. Now:
```
import _ from 'lodash-es';  // have to import whole library
import map from 'lodash-es/map';  // or have to import every function separately
import _ from '../path/to/generated/lodash-es';  // or have to write full path to generated lodash module
```
2. With this feature will be:
```
import _ from '@lodash';        // or
import map from '@lodash';
```

**Comment by mkay581** [comment]
@stat92 isn't this the similar to what I proposed a few days ago in https://github.com/Polymer/tools/issues/403?

**Comment by stat92** [comment]
@mkay581 it isn't. I am proposing to only replace custom namespaces with the provided pathes. And it doesn't affect the logic of the program. In your case, strict package selection can make packages not compatible. And the best way to the problem, I think, is to fork that dependent project and fixing pathes.

**Comment by Draccoz** [comment]
Personally I consider that a bad idea, as it could override npm namespaces, which could lead to a lot of issues. Say you declare the above `@lodash` namespace. Then lets assume lodash decides to drop the `lodash` npm name making it deprecated (no new code), and starts using `@lodash` but with a different code structure.
If at that point somebody from the project using the above proposal tries to use the new `@lodash` official namespace, they would get problems. Even if you throw a very verbose error saying what is wrong, it would require crawling the whole project, changing your custom namespace to be something else in order to use new `@lodash` namespace.

**Comment by stat92** [comment]
@Draccoz Thank you. Good advice. May be to prevent problems with the naming conflict devs should use original names like `@{company-name}-lodash`. How do you import libraries like lodash, ramda now? Do you import whole package or every function separately or may be in another way?

**Comment by mkay581** [comment]
@stat92 I see. I guess I misread your proposal. I went back and read it again and now I'm seeing that this is allowing a consumer of a library to override the package name. I'm not so sure if that is a good idea since it would be competing with the npm namespace.

Also, this only seems useful for packages that have lots of nested util files and don't provide a way to import util files separately, without importing all other files. How many packages actually fall into this category? I would assume not many.  And the packages that do, like `@lodash` should update their packages so that util functions can be imported separately. That being said, I think this is something that should be dealt with `@lodash` on their repository rather in on Polymer.

**Comment by Draccoz** [comment]
Usually I import from as specific paths as possible within provided repo. Registering company name specific namespaces is a bad approach as well as it could still overlap with some packages, even if not now, it might in the future.
As to your P.S., yes, devs could be aware of the change, that still doesn't help with refactoring entire codebase.

**Comment by stat92** [comment]
@mkay581 Dev will be aware of competing with npm namespace as dev will download packages manually when migrating to the new version. Say before if you did `yarn add lodash` after will `yarn add @lodash/map`.

@Draccoz I don't see a huge refactoring. Is it hard to `Ctrl+Shift+H` -> `@{company-name}-lodash` to `@{company-name}-utils` -> `Enter`?

**Comment by Draccoz** [comment]
> I think with Polymer 3.0 where build/convert step is always required this feature will not disturb the devs but will help.

This isn't 100% true. At this moment Polymer does require a build step, but once bare module specifier standard is agreed and implemented in the browsers, build step will be redundant. That means everything that goes beyond BMS known from Node.JS will be against the specs.
Again, these are my 2 cents on the topic. It's up to Polymer team anyway :P.

**Comment by stat92** [comment]
@Draccoz Yep. You are right. I suppose that will be implemented with file path mapping. And map of the files will be nice to have)
