### ISSUE TITLE
polymer test `--config-file` is ignored

### ISSUE THREAD

**Issue by ankon** [Polymer/tools#416]
`polymer test --help` says:
~~~
  --config-file string             Config file that needs to be used by wct. ie: wct.config-sauce.js             
~~~~

Looking through https://github.com/Polymer/tools/blob/219ab4f3f9f8773e75f8c6181109e8966082b9af/packages/cli/src/commands/test.ts#L139-L157: The argument is passed directly to wct's cli.

That one however expects `configFile`: https://github.com/Polymer/tools/blob/219ab4f3f9f8773e75f8c6181109e8966082b9af/packages/web-component-tester/runner/config.ts#L349-L352

I'm not sure how to resolve this, as `polymer-cli` has both options with camelCase and with dash-case.

Right now though the result of this is that `--config-file` doesn't work, and I need to do something like this in Travis: `mv travis-wct.conf.json wct.conf.json`. Clearly ugly :/

**Comment by ZempTime** [comment]
I'm running into this, too. Issue on old repo here: https://github.com/Polymer/polymer-cli/issues/919

**Comment by merlinnot** [comment]
`—configFile`

**Comment by ZempTime** [comment]
here's what happens when I attempt to use that w/ `polymer-cli`:
<img width="1108" alt="screen shot 2018-05-31 at 11 50 54 am" src="https://user-images.githubusercontent.com/3596468/40795872-ed5dccc6-64c8-11e8-8fa6-95ab5febe47a.png">

when I do
`polymer test --config-file wct.config.json`
the config gets ignored.

when I do
`wct --configFile wct.config.json`
everything works fine.

This appears to be the same issue as https://github.com/Polymer/polymer-cli/issues/919

Is this an issue where a PR would be appreciated?

**Comment by stramel** [comment]
https://github.com/Polymer/web-component-tester/pull/698/files
